# Generated by Django 5.1.7 on 2025-08-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_image_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_rounded',
            field=models.URLField(blank=True, help_text='URL da imagem redonda', null=True),
        ),
    ]
