# Generated by Django 5.2.5 on 2025-09-01 19:26

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_image_file_rounded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_key', models.UUIDField(default=uuid.uuid4, help_text='Used to attach the document to another object. Cannot be used to retrieve the document file.', unique=True)),
                ('public_id', models.CharField(help_text='Used to retrieve the document itself. Should not be readable until the document is attached to another object.', max_length=255, unique=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('folder', models.CharField(default='media/documents', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
