# Generated by Django 5.1.7 on 2025-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
