# Generated by Django 5.1.7 on 2025-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_passenger_responsible_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='passenger', to='authentication.address'),
        ),
    ]
