# Generated by Django 5.1.7 on 2025-05-10 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_parent_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='children',
            new_name='students',
        ),
    ]
