# Generated by Django 5.1.7 on 2025-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_passenger_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
