# Generated by Django 5.1.7 on 2025-05-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_address_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
