# Generated by Django 5.1.7 on 2025-05-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_children_parent_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='The children of the parent', related_name='parents', to='authentication.student'),
        ),
    ]
