# Generated by Django 5.1.7 on 2025-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_passage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='kinship',
            field=models.CharField(blank=True, choices=[('PARENTS', 'Parents'), ('BROTHERS', 'Brothers'), ('AUNTS', 'Aunts'), ('GRANDPARENTS', 'Grandparents'), ('OTHERS', 'Others')], max_length=50, null=True),
        ),
    ]
