# Generated by Django 5.1.7 on 2025-05-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_responsible_kinship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsible',
            name='kinship',
        ),
        migrations.RemoveField(
            model_name='responsible',
            name='students',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to='authentication.responsible'),
        ),
    ]
