# Generated by Django 5.1.7 on 2025-06-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_username'),
        ('uploader', '0002_image_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_picture', to='uploader.image'),
        ),
    ]
