# Generated by Django 5.1.7 on 2025-08-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
