# Generated by Django 5.1.7 on 2025-08-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_my_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
