# Generated by Django 5.1.7 on 2025-08-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_responsible_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
