# Generated by Django 5.2.5 on 2025-10-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_driver_cpf_alter_passenger_cpf'),
        ('uploader', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cnh_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_cnh_document', to='uploader.document'),
        ),
        migrations.AddField(
            model_name='driver',
            name='course_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_course_document', to='uploader.document'),
        ),
        migrations.AddField(
            model_name='driver',
            name='toxic_exam_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_toxic_exam_document', to='uploader.document'),
        ),
    ]
