from .address import AddressReadSerializer, AddressWriterSerializer, AddressPassengerSerializer
from .user import UserListSerializer, UserWriterSerializer, UserReadSerializer, CustomTokenObtainPairSerializer, UserRetrieveSerializer
from .driver import DriverReadSerializer ,DriverCreateSerializer
from .passenger import PassengerReadSerializer, PassengerCreateSerializer, StudentDataSerializer, PassengerRouteReadSerializer
from .responsible import ResponsibleReadSerializer, ResponsibleCreateSerializer