# Generated by Django 5.1.7 on 2025-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_parent_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='The children of the parent', null=True, related_name='parents', to='authentication.student'),
        ),
    ]
