# Generated by Django 5.1.7 on 2025-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(help_text='The plate of the vehicle', max_length=255)),
                ('model', models.CharField(help_text='The model of the vehicle', max_length=255)),
                ('seats', models.IntegerField(help_text='The number of seats of the vehicle')),
                ('picture', models.ImageField(help_text='The picture of the vehicle', upload_to='vehicles/')),
                ('status', models.CharField(choices=[('manutenção', 'Maintenance'), ('disponível', 'Available'), ('em rota', 'On Route')], help_text='The status of the vehicle', max_length=255)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
