# Generated by Django 5.1.7 on 2025-05-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='The type of the notify', max_length=255)),
                ('message', models.TextField(help_text='The message of the notify')),
                ('to_type', models.CharField(help_text='The type of the notify', max_length=255)),
                ('to_id', models.IntegerField(help_text='The id of the notify')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The created at of the notify')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The updated at of the notify')),
            ],
            options={
                'verbose_name': 'Notify',
                'verbose_name_plural': 'Notifies',
            },
        ),
    ]
