# Generated by Django 5.1.7 on 2025-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0002_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='to_type',
            field=models.CharField(choices=[('responsaveis', 'Parents'), ('alunos', 'Students'), ('motoristas', 'Drivers'), ('administradores', 'Admins')], help_text='The type of the notify', max_length=255),
        ),
    ]
