# Generated by Django 5.1.7 on 2025-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0003_alter_notify_to_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='to_type',
            field=models.CharField(choices=[('responsaveis', 'Parents'), ('responsavel', 'Parent'), ('alunos', 'Students'), ('aluno', 'Student'), ('motoristas', 'Drivers'), ('motorista', 'Driver'), ('administradores', 'Admins')], help_text='The type of the notify', max_length=255),
        ),
    ]
