# Generated by Django 5.1.7 on 2025-05-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0004_alter_notify_to_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=10)),
                ('entity', models.CharField(max_length=10)),
                ('entity_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goroutes_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
