# Generated by Django 5.1.7 on 2025-07-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0004_alter_notify_to_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('init_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('duration', models.FloatField()),
                ('latitude_origin', models.FloatField()),
                ('longitude_origin', models.FloatField()),
                ('latitude_destination', models.FloatField()),
                ('longitude_destination', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['created_at'],
            },
        ),
    ]
