# Generated by Django 5.1.7 on 2025-07-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_address_latitude_address_longitude'),
        ('goroutes', '0005_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='authentication.passenger')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='goroutes.route')),
            ],
        ),
    ]
