# Generated by Django 5.1.7 on 2025-07-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_address_latitude_address_longitude'),
        ('goroutes', '0006_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_route', to='authentication.passenger')),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_routes', to='goroutes.route')),
            ],
        ),
        migrations.DeleteModel(
            name='Present',
        ),
    ]
