# Generated by Django 5.1.7 on 2025-07-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_address_latitude_address_longitude'),
        ('goroutes', '0007_passengerroute_delete_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerroute',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_routes', to='authentication.passenger'),
        ),
        migrations.AlterField(
            model_name='passengerroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_routes', to='goroutes.route'),
        ),
    ]
