# Generated by Django 5.1.7 on 2025-07-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0008_alter_passengerroute_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='addresses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='route',
            name='auto_recalculate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='optimized_route_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
