# Generated by Django 5.2.1 on 2025-07-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0009_route_addresses_route_auto_recalculate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='addresses_order',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='route',
            name='final_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='link_maps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goroutes.vehicle'),
        ),
    ]
