# Generated by Django 5.1.7 on 2025-07-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0010_route_addresses_order_route_final_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='markers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='overview_polyline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
