# Generated by Django 5.1.7 on 2025-07-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0011_route_markers_route_overview_polyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='coors_passageiros',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='route',
            name='points',
            field=models.JSONField(default=list),
        ),
    ]
