# Generated by Django 5.1.7 on 2025-07-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0012_route_coors_passageiros_route_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='coors_passageiros',
            new_name='coords_passageiros',
        ),
    ]
