# Generated by Django 5.1.7 on 2025-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0013_rename_coors_passageiros_route_coords_passageiros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(blank=True, help_text='The picture of the vehicle', null=True, upload_to='vehicles/'),
        ),
    ]
