# Generated by Django 5.1.7 on 2025-07-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0015_alter_vehicle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('manutenção', 'Maintenance'), ('disponível', 'Available'), ('em rota', 'On Route')], max_length=255),
        ),
    ]
