# Generated by Django 5.1.7 on 2025-07-30 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0016_alter_vehicle_model_alter_vehicle_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='picture',
        ),
    ]
