# Generated by Django 5.1.7 on 2025-07-30 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0017_remove_vehicle_picture'),
        ('uploader', '0002_image_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_picture', to='uploader.image'),
        ),
    ]
