# Generated by Django 5.1.7 on 2025-08-11 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_my_location'),
        ('goroutes', '0019_route_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='authentication.driver'),
        ),
    ]
