# Generated by Django 5.2.5 on 2025-09-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0020_route_driver'),
        ('uploader', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='AD',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_ad', to='uploader.document'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='CRLV',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_crlv', to='uploader.document'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='CV',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_cv', to='uploader.document'),
        ),
    ]
