# Generated by Django 5.2.5 on 2025-09-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_driver_cpf_alter_passenger_cpf'),
        ('goroutes', '0021_vehicle_ad_vehicle_crlv_vehicle_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('init_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('latitude_origin', models.FloatField()),
                ('longitude_origin', models.FloatField()),
                ('latitude_destination', models.FloatField()),
                ('longitude_destination', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_recalculate', models.BooleanField(default=False)),
                ('addresses', models.JSONField(default=list)),
                ('optimized_route_url', models.URLField(blank=True, null=True)),
                ('overview_polyline', models.JSONField(blank=True, null=True)),
                ('markers', models.JSONField(blank=True, null=True)),
                ('coords_passageiros', models.JSONField(default=list)),
                ('points', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_routes', to='authentication.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_routes', to='goroutes.route')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_routes', to='goroutes.vehicle')),
            ],
            options={
                'verbose_name': 'Daily Route',
                'verbose_name_plural': 'Daily Routes',
                'ordering': ['-date', 'init_hour'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('daily_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='goroutes.dailyroute')),
                ('passenger_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='authentication.passenger')),
            ],
            options={
                'verbose_name': 'Presence',
                'verbose_name_plural': 'Presences',
                'unique_together': {('daily_route', 'passenger_route')},
            },
        ),
    ]
