# Generated by Django 5.2.5 on 2025-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0022_dailyroute_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroute',
            name='original',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
