# Generated by Django 5.2.5 on 2025-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0023_dailyroute_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='present',
        ),
        migrations.AddField(
            model_name='presence',
            name='status',
            field=models.CharField(choices=[('PRESENTE', 'Present'), ('FALTOU', 'FALTOU'), ('NAO_PEGO', 'NAO_PEGO')], default='NAO_PEGO', max_length=10),
        ),
    ]
