# Generated by Django 5.2.5 on 2025-09-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0024_remove_presence_present_presence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroute',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
