# Generated by Django 5.2.5 on 2025-09-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0025_dailyroute_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCacheRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.TextField()),
                ('destino', models.TextField()),
                ('distancia_metros', models.IntegerField()),
                ('duracao_segundos', models.IntegerField()),
                ('polyline', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rotas_cache',
                'unique_together': {('origem', 'destino')},
            },
        ),
    ]
