# Generated by Django 5.2.5 on 2025-09-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0026_datacacheroute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacacheroute',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='datacacheroute',
            old_name='destino',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='datacacheroute',
            old_name='distancia_metros',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='datacacheroute',
            old_name='duracao_segundos',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='datacacheroute',
            old_name='origem',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='datacacheroute',
            old_name='data_atualizacao',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='datacacheroute',
            unique_together={('origin', 'destination')},
        ),
        migrations.AddField(
            model_name='datacacheroute',
            name='latitude_destination',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacacheroute',
            name='latitude_origin',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacacheroute',
            name='longitude_destination',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacacheroute',
            name='longitude_origin',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
