# Generated by Django 5.2.5 on 2025-09-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0027_rename_data_criacao_datacacheroute_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerroute',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
