# Generated by Django 5.2.5 on 2025-09-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0028_passengerroute_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerroute',
            name='order',
        ),
    ]
