# Generated by Django 5.2.5 on 2025-10-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0029_remove_passengerroute_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passengerroute',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='passengerroute',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
