# Generated by Django 5.2.5 on 2025-10-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0030_alter_passengerroute_options_passengerroute_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Manutencao', 'Maintenance'), ('Disponivel', 'Available'), ('Em rota', 'On Route')], max_length=255),
        ),
    ]
