# Generated by Django 5.2.5 on 2025-11-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroutes', '0031_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroute',
            name='optimized_route_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
