# Generated by Django 5.2.5 on 2025-11-03 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_driver_cnh_document_driver_course_document_and_more'),
        ('goroutes', '0032_alter_dailyroute_optimized_route_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='authentication.driver'),
        ),
    ]
